In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
import numpy as np
from random import randint

import matplotlib.pyplot as plt
%matplotlib inline

batch_size = 25
train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.ToTensor()),
        batch_size = 10000, shuffle=True)

from random import randint

In [2]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
if device != 'cpu':
    torch.set_default_tensor_type('torch.cuda.FloatTensor')

num_classes=10

class EncoderRNN(nn.Module):
    def __init__(self, input_size, hidden_size, n_layers=3, dropout=0):
        super(EncoderRNN, self).__init__()
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.n_layers = n_layers
        self.dropout = dropout
        
        self.gru = nn.GRU(input_size, hidden_size, n_layers, dropout=self.dropout, bidirectional=True)
        self.hidden = None
    def forward(self, input_seqs, input_lengths):

        input_seqs = input_seqs.unsqueeze(-1).type(torch.FloatTensor)
        packed = torch.nn.utils.rnn.pack_padded_sequence(input_seqs, input_lengths)
        outputs, self.hidden = self.gru(packed, self.hidden)
        outputs, output_lengths = torch.nn.utils.rnn.pad_packed_sequence(outputs) 
        outputs = outputs[:, :, :self.hidden_size] + outputs[:, : ,self.hidden_size:] 
        
        return outputs

In [3]:
class CircuitNet(nn.Module):
    def __init__(self,num_classes=12,num_lstm_layers=3):
        super(CircuitNet, self).__init__()
        
        
        self.state_size = 100
        self.num_lstm_layers = num_lstm_layers
        
        #monitor use of each circuit to balance training
        self.used_circuits = np.zeros([40,2])
        for i in range(40):
            self.used_circuits[i][0] = i
        
        
        
        self.circuits_to_use = 5
        self.n_circuits = 10
        self.circuit_in_dim = 4
        #self.circuit_in_x = 2
        #self.circuit_in_y = 2
        
        #circuit picker
        self.circuit_picker = nn.Sequential(
            nn.Conv1d(1, 16, 3, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(16),
            nn.MaxPool1d(2, stride=2),  
            nn.Conv1d(16, 8, 3, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(8),
            nn.MaxPool1d(2, stride=2)
        )
        
        self.circuit_picker_out = nn.LSTM(1568,(self.n_circuits *  self.circuits_to_use), self.num_lstm_layers)
        self.hidden = None
        #self.circuit_picker_out = nn.Linear(8*7*7, (self.n_circuits *  self.circuits_to_use))
        
        #data pipe
        self.data_pipe = nn.Sequential(
            nn.Conv1d(1, 4, 4, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(4),
            nn.Conv1d(4, 8, 4, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(8),
            nn.MaxPool1d(2, stride=2), 
            
            
            nn.Conv1d(8, 4, 4, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(4),
            nn.Conv1d(4, 8, 4, stride=1, padding=1),  
            nn.ReLU(True),
            nn.BatchNorm1d(8),
            nn.MaxPool1d(2, stride=2)
        )
        self.data_pipe_out = nn.Linear(1560, (self.circuits_to_use * self.circuit_in_dim))
        
            
        self.circuits = []
        #define circuits
        for i in range(self.n_circuits):
        
            
            self.circuits.append(nn.Sequential(
                nn.Conv1d(1, 8, kernel_size=2, stride=1, padding=1),
                nn.BatchNorm1d(8),
                nn.ReLU(True),
                #nn.MaxPool2d(kernel_size=2, stride=2)))
            
                nn.Conv1d(8, 16, kernel_size=2, stride=1, padding=1),
                nn.BatchNorm1d(16),
                nn.ReLU(True),
                
                nn.MaxPool1d(kernel_size=2, stride=2)))
        
        #connect circuits (this is temporary)
        self.connect = nn.Sequential(
            nn.Linear(1440, 28*28))
        
        #final circuit to prediction
        self.output = nn.Sequential(
            #nn.Linear(640, 400),
            nn.Linear(240, num_classes))
        
    #init hidden state for lstm layer
    def init_hidden(self):
        return (torch.zeros(self.num_lstm_layers,1, (self.n_circuits *  self.circuits_to_use), device=device),
                torch.zeros(self.num_lstm_layers,1, (self.n_circuits *  self.circuits_to_use), device=device))
    
    def connection(self,x,verbose,circuit_dropout,circuit_ban_rate):
        x_flat = x.view(x.size(0),x.size(1),x.size(2)*x.size(3))
        circuit_pick = self.circuit_picker(x_flat)
        circuit_pick = circuit_pick.view(circuit_pick.size(0),1, -1)
        
        circuit_pick, self.hidden = self.circuit_picker_out(circuit_pick,self.hidden)
        
        
        circuit_pick = circuit_pick.view(circuit_pick.size(0),self.circuits_to_use,self.n_circuits)
        circuit_pick = circuit_pick.max(2)[1]
        
        data_pipe_in = torch.cat((circuit_pick.unsqueeze(1).type(torch.cuda.FloatTensor),x_flat),2)
        #circuit_pick_padded = F.pad(circuit_pick,(0,28-circuit_pick.size(1))).unsqueeze(1).unsqueeze(1)
        #circuit_pick_padded = circuit_pick_padded.type(torch.cuda.FloatTensor)
        #data_pipe_in = torch.cat((circuit_pick_padded,x),2)
        #data_pipe_in = data_pipe_in.view(data_pipe_in.size(0),data_pipe_in.size(1),
        #                                 data_pipe_in.size(2)*data_pipe_in.size(3))
        
        data_pipe = self.data_pipe(data_pipe_in)

        data_pipe = data_pipe.view(data_pipe.size(0), -1)
        data_pipe = self.data_pipe_out(data_pipe)
        data_pipe = data_pipe.view(data_pipe.size(0),self.circuits_to_use,self.circuit_in_dim)
        bans = np.random.randint(self.n_circuits,size=int(circuit_ban_rate*self.n_circuits))
        circuit_out = []
        for i in range(self.circuits_to_use):
            circuit_idx = circuit_pick[:,i]
            if(verbose):
                print(str(circuit_idx.cpu().numpy()))
                
            batch = []
            for b in range(batch_size):
                #print(data_pipe[b][i].shape)
                data = data_pipe[b][i]#.view(data_pipe[b][i].size(0)*data_pipe[b][i].size(1))
                data = data.unsqueeze(0).unsqueeze(0)
                circuit = self.circuits[circuit_idx[b]](data)
                #apply dropout
                if randint(1,100) < circuit_dropout*100 or circuit_idx[b] in bans:
                    circuit = torch.zeros(circuit.shape,device=device)  
                
                batch.append(circuit)
            batch = torch.cat(batch,0)
            circuit_out.append(batch)
        circuit_out = torch.cat(circuit_out,1)
        return circuit_out
    
    def forward(self, x, verbose,circuit_dropout=0,circuit_ban_rate = 0):
        
        circuit_out1 = self.connection(x,verbose,circuit_dropout,circuit_ban_rate)
        circuit_out_flat1 = circuit_out1.view(circuit_out1.size(0), -1)
        
        #connect = self.connect(circuit_out_flat1)
        #connect = connect.view(connect.size(0),1,28,28)
        
       # circuit_out2 = self.connection(connect,verbose)
        #circuit_out_flat2 = circuit_out2.view(circuit_out2.size(0), -1)
        out = self.output(circuit_out_flat1)
        
        return out
    
        

if device != 'cpu':
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
model = CircuitNet().to(device)
torch.set_default_tensor_type('torch.FloatTensor')

for batch_idx, (data, target) in enumerate(train_loader):
    data, target = data.to(device)[0:batch_size], target.to(device)[0:batch_size]
    output = model(data,False)
    break

In [4]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
optimizer2 = torch.optim.Adam(model.parameters(), lr=0.001)

model.train()
iter_print = 50

for batch_idx, (data_, target_) in enumerate(train_loader):
    #print(target)
   
    
    
    #train on digits 1-6, then train on 7-9 to check adaptability
    for i in range(1000):
        try:
            rand = randint(0, 3000)
            indices = np.where(target_<6)[0][rand:rand+batch_size]
            #indices = 
            data = np.take(data_,indices,axis = 0)
            target = np.take(target_,indices)

           # print(np.where(target_<6)[0][0:batch_size])
            data, target = data.to(device), target.to(device)

            optimizer.zero_grad()
            verbose = False
            if(i % iter_print == 0):
                verbose = True
            output = model(data,verbose,circuit_dropout=0.5,circuit_ban_rate = 0.2)
            loss =  nn.CrossEntropyLoss()(output, target)
            #loss = (output-target)**2
            loss.backward()
            optimizer.step()

            model.hidden = None
            if(i % iter_print == 0):
                print("Index : {}  Loss : {:.5f}  Real : {}  Pred : {}".format(i,
                                                                               loss[0],target[0:4].cpu().numpy(),
                                                                               output[0:4].max(1)[1].cpu().numpy()))
        except:
            continue
    print("switch")
    for i in range(500):
        try:
            rand = randint(0, 3000)
            indices = np.where(target_>6)[0][rand:rand+batch_size]
            #indices = 
            data = np.take(data_,indices,axis = 0)
            target = np.take(target_,indices)

           # print(np.where(target_<6)[0][0:batch_size])
            data, target = data.to(device), target.to(device)

            optimizer2.zero_grad()
            verbose = False
            if(batch_idx % iter_print == 0):
                verbose = False
            output = model(data,verbose)
            loss =  nn.CrossEntropyLoss()(output, target)
            #loss = (output-target)**2
            loss.backward()
            optimizer2.step()

            model.hidden = None
            if(i % 1 == 0):
                print("Index : {}  Loss : {:.5f}  Real : {}  Pred : {}".format(i,
                                                                               loss[0],target[0:4].cpu().numpy(),
                                                                               output[0:4].max(1)[1].cpu().numpy()))
        except:
            continue

[3 3 3 3 3 3 3 3 3 3 3 7 7 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[1 8 1 8 1 8 1 1 1 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 5 5 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 0  Loss : 2.59900  Real : [1 5 1 3]  Pred : [2 2 5 2]


/home/liam/.local/lib/python3.6/site-packages/ipykernel_launcher.py:37: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


[7 7 3 3 3 3 3 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 0 0 0 8 8 8 8 8 8 8 0 0 0 0 0 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 8 8 8 1 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 9]
Index : 50  Loss : 1.64378  Real : [4 5 2 3]  Pred : [4 4 3 3]
[7 7 7 7 7 7 7 3 3 3 3 3 3 3 3 3 3 7 7 7 7 7 7 3 3]
[0 0 0 0 8 8 8 8 8 0 0 0 0 8 8 8 0 8 8 8 0 0 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 9 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 100  Loss : 1.33353  Real : [5 1 5 1]  Pred : [5 3 4 1]
[7 7 7 7 3 3 3 3 7 3 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 8 8 8 8 8 8 8 8 8 8 0 0 0 8 8 8 8 8 8 8 8 0 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 9 9 9 3 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 150  Loss : 1.65622  Real : [5 2 5 1]  Pred : [3 4 4 1]
[7 1 3 3 3 3 3 3 3 3 3 3 3 3 

/home/liam/.local/lib/python3.6/site-packages/ipykernel_launcher.py:66: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


Index : 1  Loss : 19.36314  Real : [7 7 9 8]  Pred : [2 3 4 0]
Index : 2  Loss : 18.16372  Real : [7 7 7 9]  Pred : [4 4 1 4]
Index : 3  Loss : 18.70539  Real : [8 7 7 7]  Pred : [5 4 3 3]
Index : 4  Loss : 17.56542  Real : [7 7 9 7]  Pred : [3 3 3 3]
Index : 5  Loss : 17.09635  Real : [7 8 8 7]  Pred : [0 5 3 3]
Index : 6  Loss : 16.62674  Real : [8 8 8 7]  Pred : [3 3 0 3]
Index : 7  Loss : 15.77961  Real : [8 9 8 7]  Pred : [0 4 3 3]
Index : 8  Loss : 15.38437  Real : [9 9 9 7]  Pred : [4 4 3 3]
Index : 9  Loss : 14.49532  Real : [9 7 8 8]  Pred : [3 4 0 3]
Index : 10  Loss : 14.26963  Real : [9 7 8 9]  Pred : [4 3 0 3]
Index : 11  Loss : 14.25611  Real : [8 7 7 7]  Pred : [0 4 3 3]
Index : 12  Loss : 13.67064  Real : [8 7 9 8]  Pred : [3 3 3 3]
Index : 13  Loss : 13.19478  Real : [9 9 7 8]  Pred : [4 0 3 3]
Index : 14  Loss : 13.23779  Real : [9 8 9 7]  Pred : [3 0 4 3]
Index : 15  Loss : 12.91413  Real : [8 7 8 9]  Pred : [5 3 5 4]
Index : 16  Loss : 12.41157  Real : [9 9 7 8]  Pr

Index : 132  Loss : 0.97737  Real : [7 7 8 7]  Pred : [9 7 8 7]
Index : 133  Loss : 1.08103  Real : [8 9 7 7]  Pred : [8 9 9 7]
Index : 134  Loss : 0.94876  Real : [8 9 8 8]  Pred : [8 7 8 8]
Index : 135  Loss : 0.97376  Real : [8 9 9 7]  Pred : [8 9 9 7]
Index : 136  Loss : 1.04017  Real : [9 9 7 7]  Pred : [7 7 9 7]
Index : 137  Loss : 1.03616  Real : [8 8 9 9]  Pred : [8 8 7 7]
Index : 138  Loss : 1.01164  Real : [9 7 7 7]  Pred : [7 7 7 7]
Index : 139  Loss : 0.97213  Real : [8 7 9 8]  Pred : [8 9 7 8]
Index : 140  Loss : 1.07242  Real : [8 7 9 9]  Pred : [8 7 7 7]
Index : 141  Loss : 0.99706  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 142  Loss : 0.97304  Real : [9 9 7 7]  Pred : [7 8 9 7]
Index : 143  Loss : 0.88856  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 144  Loss : 0.97021  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 145  Loss : 0.96588  Real : [9 9 9 8]  Pred : [9 7 9 8]
Index : 146  Loss : 0.93772  Real : [8 8 7 7]  Pred : [8 8 7 7]
Index : 147  Loss : 0.96150  Real : [7 8

Index : 264  Loss : 0.39704  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 265  Loss : 0.52259  Real : [7 9 9 8]  Pred : [7 7 9 8]
Index : 266  Loss : 0.37766  Real : [8 9 9 9]  Pred : [8 9 7 9]
Index : 267  Loss : 0.54546  Real : [7 8 7 7]  Pred : [9 8 7 7]
Index : 268  Loss : 0.50608  Real : [8 7 7 7]  Pred : [8 7 8 7]
Index : 269  Loss : 0.40115  Real : [8 8 7 7]  Pred : [8 8 9 7]
Index : 270  Loss : 0.45311  Real : [8 9 9 7]  Pred : [8 9 9 8]
Index : 271  Loss : 0.29443  Real : [7 8 7 7]  Pred : [7 8 7 7]
Index : 272  Loss : 0.35771  Real : [9 9 9 9]  Pred : [7 9 9 9]
Index : 273  Loss : 0.31388  Real : [7 7 9 8]  Pred : [7 7 7 8]
Index : 274  Loss : 0.36560  Real : [8 7 9 8]  Pred : [8 7 9 8]
Index : 275  Loss : 0.32846  Real : [8 7 7 9]  Pred : [8 7 9 9]
Index : 276  Loss : 0.26167  Real : [8 7 9 9]  Pred : [8 7 9 9]
Index : 277  Loss : 0.33157  Real : [9 7 9 8]  Pred : [9 7 9 8]
Index : 278  Loss : 0.23102  Real : [8 9 7 7]  Pred : [8 9 7 7]
Index : 279  Loss : 0.39429  Real : [7 8

Index : 395  Loss : 0.32442  Real : [9 8 8 8]  Pred : [9 8 8 8]
Index : 396  Loss : 0.07836  Real : [8 7 7 8]  Pred : [8 7 7 8]
Index : 397  Loss : 0.16442  Real : [7 9 7 7]  Pred : [7 9 7 7]
Index : 398  Loss : 0.10171  Real : [9 9 8 8]  Pred : [9 9 8 8]
Index : 399  Loss : 0.11654  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 400  Loss : 0.14565  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 401  Loss : 0.23157  Real : [7 8 7 8]  Pred : [7 8 9 8]
Index : 402  Loss : 0.14620  Real : [9 9 8 9]  Pred : [9 9 8 9]
Index : 403  Loss : 0.10058  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 404  Loss : 0.21502  Real : [9 8 9 7]  Pred : [9 8 9 7]
Index : 405  Loss : 0.17954  Real : [8 9 7 8]  Pred : [8 9 7 8]
Index : 406  Loss : 0.10944  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 407  Loss : 0.11860  Real : [9 7 9 7]  Pred : [9 7 9 7]
Index : 408  Loss : 0.19423  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 409  Loss : 0.07897  Real : [9 7 7 8]  Pred : [9 7 7 8]
Index : 410  Loss : 0.21099  Real : [9 7

[7 7 7 7 7 7 7 7 3 3 3 3 3 3 3 7 7 7 3 3 3 3 3 3 3]
[0 0 0 8 0 8 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 250  Loss : 0.59468  Real : [4 5 2 5]  Pred : [4 5 2 0]
[7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 9 9 9 9 9 7 7 7 7 7 7 7 7 7 7 7 7 7 1 7 7]
Index : 300  Loss : 0.39908  Real : [3 5 0 0]  Pred : [3 5 0 0]
[7 7 3 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 7 3 3 3 3 3 3]
[0 8 8 8 8 8 8 0 8 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 350  Loss : 0.14114  Real : [2 0 1 5]  Pred : [2 0 1 5]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3

Index : 54  Loss : 0.31278  Real : [9 9 8 8]  Pred : [7 9 8 8]
Index : 55  Loss : 0.47464  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 56  Loss : 0.47639  Real : [7 8 9 7]  Pred : [7 8 9 7]
Index : 57  Loss : 0.27264  Real : [8 8 7 9]  Pred : [8 8 7 9]
Index : 58  Loss : 0.46438  Real : [7 7 7 7]  Pred : [7 7 9 7]
Index : 59  Loss : 0.43956  Real : [7 7 8 9]  Pred : [7 7 8 9]
Index : 60  Loss : 0.25744  Real : [9 7 8 8]  Pred : [9 7 8 8]
Index : 61  Loss : 0.46787  Real : [9 9 7 7]  Pred : [9 9 7 7]
Index : 62  Loss : 0.34627  Real : [9 9 8 8]  Pred : [9 9 8 8]
Index : 63  Loss : 0.26086  Real : [8 9 8 9]  Pred : [8 9 8 9]
Index : 64  Loss : 0.37012  Real : [8 8 8 7]  Pred : [8 8 8 7]
Index : 65  Loss : 0.34273  Real : [7 7 8 8]  Pred : [7 7 8 8]
Index : 66  Loss : 0.29916  Real : [7 9 9 9]  Pred : [7 9 9 9]
Index : 67  Loss : 0.24283  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 68  Loss : 0.53082  Real : [7 7 8 9]  Pred : [9 7 8 9]
Index : 69  Loss : 0.25189  Real : [7 8 9 9]  Pred : [7

Index : 186  Loss : 0.15279  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 187  Loss : 0.16476  Real : [7 9 9 8]  Pred : [7 8 9 8]
Index : 188  Loss : 0.32668  Real : [8 8 9 9]  Pred : [8 8 9 9]
Index : 189  Loss : 0.16080  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 190  Loss : 0.13874  Real : [8 8 8 8]  Pred : [9 8 8 8]
Index : 191  Loss : 0.22713  Real : [9 8 9 8]  Pred : [9 8 9 8]
Index : 192  Loss : 0.37021  Real : [7 9 8 7]  Pred : [7 9 8 9]
Index : 193  Loss : 0.08124  Real : [7 9 9 7]  Pred : [7 9 9 7]
Index : 194  Loss : 0.23939  Real : [9 7 9 7]  Pred : [7 7 9 7]
Index : 195  Loss : 0.05030  Real : [9 8 9 7]  Pred : [9 8 9 7]
Index : 197  Loss : 0.12455  Real : [9 8 8 7]  Pred : [9 8 8 7]
Index : 198  Loss : 0.08588  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 199  Loss : 0.25166  Real : [8 9 8 9]  Pred : [8 9 8 9]
Index : 200  Loss : 0.11027  Real : [7 7 9 7]  Pred : [7 7 9 7]
Index : 201  Loss : 0.19837  Real : [9 9 8 8]  Pred : [9 9 8 8]
Index : 202  Loss : 0.11200  Real : [8 8

Index : 318  Loss : 0.13134  Real : [7 8 7 7]  Pred : [7 8 7 7]
Index : 319  Loss : 0.04882  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 320  Loss : 0.04881  Real : [7 9 9 9]  Pred : [7 9 9 9]
Index : 321  Loss : 0.05519  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 322  Loss : 0.03066  Real : [7 7 9 8]  Pred : [7 7 9 8]
Index : 323  Loss : 0.14879  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 324  Loss : 0.09086  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 325  Loss : 0.08760  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 326  Loss : 0.07193  Real : [8 8 8 7]  Pred : [8 8 8 7]
Index : 327  Loss : 0.13967  Real : [8 8 8 9]  Pred : [8 8 8 8]
Index : 328  Loss : 0.21110  Real : [8 7 8 7]  Pred : [8 7 8 7]
Index : 329  Loss : 0.07007  Real : [9 9 8 7]  Pred : [9 9 8 7]
Index : 330  Loss : 0.05004  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 331  Loss : 0.04344  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 332  Loss : 0.15569  Real : [9 9 9 7]  Pred : [9 9 9 7]
Index : 333  Loss : 0.05162  Real : [8 7

Index : 448  Loss : 0.13661  Real : [8 8 9 9]  Pred : [8 8 9 9]
Index : 449  Loss : 0.03942  Real : [8 8 7 9]  Pred : [8 8 7 9]
Index : 450  Loss : 0.03146  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 451  Loss : 0.07399  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 452  Loss : 0.09417  Real : [7 9 9 9]  Pred : [7 9 9 9]
Index : 453  Loss : 0.04670  Real : [9 8 9 9]  Pred : [9 8 9 9]
Index : 454  Loss : 0.13717  Real : [7 8 7 9]  Pred : [9 8 7 9]
Index : 455  Loss : 0.04936  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 456  Loss : 0.06947  Real : [9 7 9 8]  Pred : [9 7 9 8]
Index : 457  Loss : 0.11305  Real : [7 7 7 7]  Pred : [7 7 7 9]
Index : 458  Loss : 0.06690  Real : [9 8 7 8]  Pred : [9 8 7 8]
Index : 459  Loss : 0.07429  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 460  Loss : 0.06338  Real : [8 9 7 9]  Pred : [8 9 7 9]
Index : 461  Loss : 0.04786  Real : [9 9 8 7]  Pred : [9 9 8 7]
Index : 462  Loss : 0.02077  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 463  Loss : 0.23805  Real : [7 7

[7 7 7 7 7 7 7 7 3 3 3 7 7 7 7 7 7 7 7 7 3 3 3 3 3]
[0 0 0 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 9 9 9 7 7 7 7 7 7 7 7 7 7 7]
Index : 800  Loss : 0.27805  Real : [5 0 1 5]  Pred : [1 0 1 5]
[7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 0 0 0 8 8 8 8 8 8 0 0 0 0 0 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 9]
Index : 850  Loss : 0.32306  Real : [1 0 0 2]  Pred : [1 0 0 2]
[7 7 7 7 7 3 3 3 3 3 3 3 3 3 7 7 7 7 7 7 7 7 7 7 7]
[0 0 0 8 8 8 8 8 8 8 8 8 0 0 0 0 0 0 0 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 9 9 9 7 7 7 7]
Index : 900  Loss : 0.08147  Real : [2 3 2 2]  Pred : [2 3 2 2]
[7 7 7 7 7 7 7 7 3 3 3 7 3 3

Index : 111  Loss : 0.06281  Real : [8 7 7 9]  Pred : [8 7 7 9]
Index : 112  Loss : 0.09469  Real : [7 9 9 7]  Pred : [7 9 9 7]
Index : 113  Loss : 0.05881  Real : [7 7 9 9]  Pred : [7 7 9 9]
Index : 114  Loss : 0.15218  Real : [8 7 8 8]  Pred : [8 7 8 8]
Index : 115  Loss : 0.09788  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 116  Loss : 0.36284  Real : [9 9 8 8]  Pred : [7 9 8 8]
Index : 117  Loss : 0.09974  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 118  Loss : 0.28610  Real : [8 8 7 7]  Pred : [8 8 9 7]
Index : 119  Loss : 0.08028  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 120  Loss : 0.06403  Real : [7 8 7 9]  Pred : [7 8 7 9]
Index : 121  Loss : 0.10704  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 122  Loss : 0.12275  Real : [9 8 8 7]  Pred : [9 8 8 7]
Index : 123  Loss : 0.09474  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 124  Loss : 0.04371  Real : [8 7 9 9]  Pred : [8 7 9 9]
Index : 125  Loss : 0.06063  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 126  Loss : 0.12575  Real : [9 8

Index : 241  Loss : 0.26401  Real : [9 9 9 7]  Pred : [9 7 9 7]
Index : 242  Loss : 0.09372  Real : [8 9 7 9]  Pred : [8 9 7 9]
Index : 243  Loss : 0.07738  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 244  Loss : 0.04631  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 245  Loss : 0.06135  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 246  Loss : 0.17047  Real : [8 8 8 8]  Pred : [8 8 8 8]
Index : 247  Loss : 0.02289  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 248  Loss : 0.05503  Real : [9 7 8 7]  Pred : [9 7 8 7]
Index : 249  Loss : 0.21123  Real : [9 9 8 7]  Pred : [9 9 7 7]
Index : 250  Loss : 0.09802  Real : [7 9 8 9]  Pred : [7 9 8 9]
Index : 251  Loss : 0.19142  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 252  Loss : 0.13875  Real : [8 8 7 7]  Pred : [8 8 9 7]
Index : 253  Loss : 0.03427  Real : [9 8 7 8]  Pred : [9 8 7 8]
Index : 254  Loss : 0.15979  Real : [9 7 9 8]  Pred : [9 7 9 8]
Index : 255  Loss : 0.04345  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 256  Loss : 0.06036  Real : [8 7

Index : 371  Loss : 0.01140  Real : [9 7 8 9]  Pred : [9 7 8 9]
Index : 372  Loss : 0.04784  Real : [7 9 8 8]  Pred : [7 9 8 8]
Index : 373  Loss : 0.05710  Real : [7 8 8 8]  Pred : [7 8 8 8]
Index : 374  Loss : 0.31028  Real : [9 9 9 9]  Pred : [9 9 9 7]
Index : 375  Loss : 0.06720  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 376  Loss : 0.04822  Real : [9 9 8 8]  Pred : [9 9 8 8]
Index : 377  Loss : 0.27985  Real : [7 7 8 8]  Pred : [7 7 8 8]
Index : 378  Loss : 0.02676  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 379  Loss : 0.04532  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 380  Loss : 0.03890  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 381  Loss : 0.01030  Real : [8 9 9 9]  Pred : [8 9 9 9]
Index : 382  Loss : 0.10426  Real : [8 9 9 8]  Pred : [8 8 9 8]
Index : 383  Loss : 0.11037  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 384  Loss : 0.04709  Real : [8 9 9 9]  Pred : [8 9 9 9]
Index : 385  Loss : 0.07845  Real : [8 9 8 9]  Pred : [8 9 8 9]
Index : 386  Loss : 0.01654  Real : [8 8

[7 7 7 3 3 3 7 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 3 7 7 7 7 7 7]
Index : 0  Loss : 2.61830  Real : [5 3 1 4]  Pred : [5 8 1 5]
[7 7 7 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 50  Loss : 0.58161  Real : [4 0 2 1]  Pred : [4 0 2 1]
[7 3 3 3 3 3 3 3 3 3 3 3 3 3 7 7 7 7 3 3 3 3 3 3 3]
[0 0 0 0 0 8 8 8 8 8 8 8 8 8 8 8 8 0 0 0 0 0 0 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 1 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 100  Loss : 0.17019  Real : [0 0 0 2]  Pred : [0 0 0 2]
[1 1 1 3 3 3 3 3 7 3 7 3 3 3 3 

Index : 29  Loss : 0.27392  Real : [7 7 8 7]  Pred : [7 7 8 7]
Index : 30  Loss : 0.14226  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 31  Loss : 0.29303  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 32  Loss : 0.12987  Real : [9 8 7 8]  Pred : [7 8 7 8]
Index : 34  Loss : 0.31426  Real : [9 9 8 9]  Pred : [9 8 8 9]
Index : 35  Loss : 0.20028  Real : [7 8 9 8]  Pred : [7 8 8 9]
Index : 36  Loss : 0.12433  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 37  Loss : 0.17766  Real : [8 8 9 7]  Pred : [8 8 9 9]
Index : 38  Loss : 0.09864  Real : [8 9 7 8]  Pred : [8 9 7 8]
Index : 39  Loss : 0.31470  Real : [9 9 9 7]  Pred : [7 9 9 7]
Index : 40  Loss : 0.16998  Real : [8 8 7 7]  Pred : [8 8 9 9]
Index : 41  Loss : 0.07052  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 42  Loss : 0.13607  Real : [8 7 7 8]  Pred : [8 7 7 8]
Index : 43  Loss : 0.20581  Real : [7 7 7 8]  Pred : [9 7 7 8]
Index : 44  Loss : 0.21772  Real : [7 8 7 8]  Pred : [7 8 7 8]
Index : 45  Loss : 0.14154  Real : [7 9 9 9]  Pred : [7

Index : 161  Loss : 0.02968  Real : [7 7 7 7]  Pred : [7 7 7 7]
Index : 162  Loss : 0.12594  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 163  Loss : 0.08340  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 164  Loss : 0.12818  Real : [9 7 9 8]  Pred : [9 7 7 8]
Index : 165  Loss : 0.11002  Real : [9 8 9 8]  Pred : [9 9 9 8]
Index : 166  Loss : 0.25954  Real : [8 7 9 8]  Pred : [8 7 9 8]
Index : 167  Loss : 0.14938  Real : [8 7 7 8]  Pred : [8 7 7 8]
Index : 168  Loss : 0.11548  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 169  Loss : 0.06196  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 170  Loss : 0.05813  Real : [8 7 7 9]  Pred : [8 7 7 9]
Index : 171  Loss : 0.26526  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 172  Loss : 0.09007  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 173  Loss : 0.04156  Real : [7 8 9 8]  Pred : [7 8 9 8]
Index : 174  Loss : 0.02284  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 175  Loss : 0.07619  Real : [7 7 7 7]  Pred : [7 7 7 7]
Index : 176  Loss : 0.06023  Real : [7 9

Index : 292  Loss : 0.04012  Real : [8 8 7 8]  Pred : [8 8 7 8]
Index : 293  Loss : 0.01371  Real : [7 8 8 7]  Pred : [7 8 8 7]
Index : 294  Loss : 0.12786  Real : [7 7 9 9]  Pred : [7 7 9 9]
Index : 295  Loss : 0.08149  Real : [8 7 7 9]  Pred : [8 7 7 9]
Index : 296  Loss : 0.11899  Real : [8 7 8 7]  Pred : [8 7 8 7]
Index : 297  Loss : 0.04246  Real : [8 8 9 8]  Pred : [8 8 9 8]
Index : 298  Loss : 0.06688  Real : [9 8 7 9]  Pred : [9 8 7 9]
Index : 299  Loss : 0.05163  Real : [7 8 9 7]  Pred : [7 8 9 7]
Index : 300  Loss : 0.03789  Real : [9 9 7 8]  Pred : [9 9 7 8]
Index : 301  Loss : 0.07436  Real : [8 7 7 8]  Pred : [8 7 7 8]
Index : 302  Loss : 0.01441  Real : [7 7 7 9]  Pred : [7 7 7 9]
Index : 303  Loss : 0.03874  Real : [7 7 7 9]  Pred : [7 7 7 9]
Index : 304  Loss : 0.03460  Real : [9 8 9 9]  Pred : [9 8 9 9]
Index : 305  Loss : 0.01977  Real : [7 9 7 8]  Pred : [7 9 7 8]
Index : 306  Loss : 0.19016  Real : [9 7 9 9]  Pred : [9 9 9 7]
Index : 307  Loss : 0.05643  Real : [8 7

Index : 427  Loss : 0.15887  Real : [7 7 8 8]  Pred : [7 7 8 7]
Index : 428  Loss : 0.05719  Real : [9 9 8 7]  Pred : [9 9 8 7]
Index : 429  Loss : 0.02810  Real : [7 8 7 9]  Pred : [7 8 7 9]
Index : 430  Loss : 0.03599  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 431  Loss : 0.05458  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 432  Loss : 0.21681  Real : [8 8 7 8]  Pred : [8 8 7 8]
Index : 433  Loss : 0.05631  Real : [7 9 7 7]  Pred : [7 9 7 7]
Index : 434  Loss : 0.08032  Real : [7 8 8 8]  Pred : [7 8 8 8]
Index : 435  Loss : 0.08843  Real : [7 9 7 7]  Pred : [7 7 7 7]
Index : 436  Loss : 0.07657  Real : [9 7 8 9]  Pred : [9 7 8 9]
Index : 437  Loss : 0.02618  Real : [9 8 7 7]  Pred : [9 8 7 7]
Index : 438  Loss : 0.05006  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 439  Loss : 0.06753  Real : [9 9 9 7]  Pred : [9 9 9 7]
Index : 440  Loss : 0.08221  Real : [7 9 8 8]  Pred : [7 9 8 8]
Index : 441  Loss : 0.10326  Real : [7 7 7 8]  Pred : [7 9 7 8]
Index : 442  Loss : 0.11626  Real : [7 8

[7 7 7 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 0 0 8 8 8 8 8 0 0 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 1 1]
Index : 550  Loss : 0.14322  Real : [2 3 2 3]  Pred : [2 3 2 3]
[7 7 7 3 3 3 3 3 3 3 7 3 3 3 3 3 3 3 3 7 7 3 3 3 3]
[0 0 0 0 8 8 8 8 8 8 8 8 8 8 0 8 8 8 8 8 8 8 8 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
Index : 600  Loss : 0.36270  Real : [2 5 2 2]  Pred : [2 5 1 2]
[7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[0 0 0 0 0 0 0 0 8 0 8 8 8 8 8 8 8 8 8 8 8 8 0 8 8]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 1 8 1 1 1 1 8 8 8]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 5 5 5 5]
Index : 650  Loss : 0.49633  Real : [2 3 4 1]  Pred : [2 3 4 1]
[7 7 7 7 3 3 3 3 3 3 3 3 3 3

Index : 85  Loss : 0.06238  Real : [8 7 7 7]  Pred : [8 7 7 7]
Index : 86  Loss : 0.02308  Real : [9 8 9 7]  Pred : [9 8 9 7]
Index : 87  Loss : 0.01757  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 88  Loss : 0.02664  Real : [8 8 9 9]  Pred : [8 8 9 9]
Index : 89  Loss : 0.16337  Real : [9 9 8 7]  Pred : [9 9 8 7]
Index : 90  Loss : 0.03484  Real : [8 9 7 9]  Pred : [8 9 7 9]
Index : 91  Loss : 0.08869  Real : [7 8 7 7]  Pred : [7 8 7 7]
Index : 92  Loss : 0.03574  Real : [9 7 9 9]  Pred : [9 7 9 9]
Index : 93  Loss : 0.12292  Real : [7 7 7 7]  Pred : [7 7 7 7]
Index : 94  Loss : 0.24109  Real : [9 9 8 8]  Pred : [7 9 8 8]
Index : 95  Loss : 0.11164  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 96  Loss : 0.25949  Real : [9 7 9 8]  Pred : [9 7 9 8]
Index : 97  Loss : 0.01660  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 98  Loss : 0.03208  Real : [9 9 9 8]  Pred : [9 9 9 8]
Index : 99  Loss : 0.15530  Real : [8 8 7 7]  Pred : [8 8 7 9]
Index : 100  Loss : 0.02952  Real : [8 9 9 7]  Pred : [

Index : 220  Loss : 0.02488  Real : [9 8 8 8]  Pred : [9 8 8 8]
Index : 221  Loss : 0.06488  Real : [8 9 9 9]  Pred : [8 9 9 9]
Index : 222  Loss : 0.25188  Real : [9 9 9 9]  Pred : [9 7 9 9]
Index : 223  Loss : 0.07244  Real : [8 7 8 7]  Pred : [8 7 8 9]
Index : 224  Loss : 0.09495  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 225  Loss : 0.05040  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 226  Loss : 0.02546  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 227  Loss : 0.03542  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 228  Loss : 0.07343  Real : [8 9 7 9]  Pred : [8 7 7 9]
Index : 229  Loss : 0.05772  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 230  Loss : 0.01201  Real : [8 8 9 8]  Pred : [8 8 9 8]
Index : 231  Loss : 0.04200  Real : [7 9 8 8]  Pred : [7 9 8 8]
Index : 232  Loss : 0.06542  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 233  Loss : 0.09436  Real : [8 7 9 7]  Pred : [8 7 9 7]
Index : 234  Loss : 0.01266  Real : [7 9 9 9]  Pred : [7 9 9 9]
Index : 235  Loss : 0.03318  Real : [7 8

Index : 351  Loss : 0.01335  Real : [9 8 8 9]  Pred : [9 8 8 9]
Index : 352  Loss : 0.09570  Real : [8 8 9 9]  Pred : [8 8 9 9]
Index : 353  Loss : 0.13159  Real : [9 8 8 8]  Pred : [9 9 8 8]
Index : 354  Loss : 0.10192  Real : [8 9 7 7]  Pred : [8 9 7 7]
Index : 355  Loss : 0.17492  Real : [7 7 7 9]  Pred : [7 7 7 9]
Index : 356  Loss : 0.05332  Real : [7 9 8 9]  Pred : [7 9 8 9]
Index : 357  Loss : 0.02397  Real : [8 7 9 9]  Pred : [8 7 9 9]
Index : 358  Loss : 0.01250  Real : [9 7 8 9]  Pred : [9 7 8 9]
Index : 359  Loss : 0.25653  Real : [9 9 7 9]  Pred : [9 9 7 9]
Index : 360  Loss : 0.02767  Real : [8 8 7 8]  Pred : [8 8 7 8]
Index : 361  Loss : 0.02481  Real : [9 9 8 9]  Pred : [9 9 8 9]
Index : 362  Loss : 0.00509  Real : [9 8 8 9]  Pred : [9 8 8 9]
Index : 363  Loss : 0.01622  Real : [9 8 7 9]  Pred : [9 8 7 9]
Index : 364  Loss : 0.21036  Real : [8 7 8 9]  Pred : [8 7 8 7]
Index : 365  Loss : 0.00720  Real : [8 8 8 9]  Pred : [8 8 8 9]
Index : 366  Loss : 0.02174  Real : [7 8

Index : 483  Loss : 0.01647  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 484  Loss : 0.04958  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 485  Loss : 0.21937  Real : [7 7 9 9]  Pred : [7 7 9 9]
Index : 486  Loss : 0.03237  Real : [8 8 8 8]  Pred : [8 8 8 8]
Index : 487  Loss : 0.05193  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 488  Loss : 0.01788  Real : [8 7 8 8]  Pred : [8 7 8 8]
Index : 489  Loss : 0.03906  Real : [8 9 8 8]  Pred : [8 9 8 8]
Index : 490  Loss : 0.12903  Real : [8 8 7 9]  Pred : [8 8 7 9]
Index : 491  Loss : 0.17946  Real : [9 9 7 9]  Pred : [9 9 7 9]
Index : 492  Loss : 0.02917  Real : [9 7 7 8]  Pred : [9 7 7 8]
Index : 493  Loss : 0.01888  Real : [9 9 7 9]  Pred : [9 9 7 9]
Index : 494  Loss : 0.04007  Real : [9 8 8 7]  Pred : [9 8 8 7]
Index : 495  Loss : 0.01065  Real : [7 8 9 8]  Pred : [7 8 9 8]
Index : 496  Loss : 0.03505  Real : [7 9 9 8]  Pred : [7 9 9 8]
Index : 497  Loss : 0.06497  Real : [7 7 7 9]  Pred : [7 7 7 9]
Index : 498  Loss : 0.05163  Real : [9 9

Index : 11  Loss : 2.24517  Real : [8 9 7 8]  Pred : [0 4 7 5]
Index : 12  Loss : 2.25230  Real : [8 7 8 7]  Pred : [1 2 2 7]
Index : 13  Loss : 1.68006  Real : [8 7 9 7]  Pred : [0 7 1 7]
Index : 14  Loss : 2.28233  Real : [8 8 8 8]  Pred : [2 8 0 0]
Index : 15  Loss : 1.77472  Real : [7 9 8 9]  Pred : [1 4 5 9]
Index : 16  Loss : 0.40964  Real : [9 7 8 7]  Pred : [7 1 0 7]
Index : 17  Loss : 0.26109  Real : [7 9 9 7]  Pred : [7 9 9 7]
Index : 18  Loss : 0.35232  Real : [7 8 7 9]  Pred : [7 8 7 9]
Index : 19  Loss : 0.31908  Real : [9 9 7 9]  Pred : [9 9 7 7]
Index : 20  Loss : 0.19816  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 21  Loss : 0.28120  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 22  Loss : 0.36804  Real : [7 8 9 7]  Pred : [7 8 4 7]
Index : 23  Loss : 0.08233  Real : [7 9 7 7]  Pred : [7 9 7 7]
Index : 24  Loss : 0.27266  Real : [7 8 9 8]  Pred : [7 8 8 8]
Index : 25  Loss : 0.08646  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 26  Loss : 0.25691  Real : [9 7 9 7]  Pred : [9

Index : 141  Loss : 0.02934  Real : [8 8 8 8]  Pred : [8 8 8 8]
Index : 142  Loss : 0.08634  Real : [8 7 9 9]  Pred : [8 7 9 9]
Index : 143  Loss : 0.02282  Real : [9 8 7 7]  Pred : [9 8 7 7]
Index : 144  Loss : 0.06338  Real : [9 7 7 8]  Pred : [9 7 7 8]
Index : 145  Loss : 0.06570  Real : [9 7 7 9]  Pred : [9 7 7 9]
Index : 146  Loss : 0.18380  Real : [8 8 7 9]  Pred : [8 8 7 9]
Index : 147  Loss : 0.09505  Real : [7 8 7 9]  Pred : [7 8 7 9]
Index : 148  Loss : 0.03179  Real : [8 8 9 7]  Pred : [8 8 9 7]
Index : 149  Loss : 0.24360  Real : [7 8 9 9]  Pred : [7 8 9 9]
Index : 150  Loss : 0.30718  Real : [7 9 8 9]  Pred : [7 9 8 9]
Index : 151  Loss : 0.02968  Real : [7 9 9 7]  Pred : [7 9 9 7]
Index : 152  Loss : 0.03376  Real : [7 9 8 8]  Pred : [7 9 8 8]
Index : 153  Loss : 0.02434  Real : [7 9 7 9]  Pred : [7 9 7 9]
Index : 154  Loss : 0.05354  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 155  Loss : 0.05944  Real : [9 7 9 7]  Pred : [9 7 9 7]
Index : 156  Loss : 0.52751  Real : [7 8

Index : 271  Loss : 0.02008  Real : [9 7 8 9]  Pred : [9 7 8 9]
Index : 272  Loss : 0.03366  Real : [7 9 7 7]  Pred : [7 9 7 7]
Index : 273  Loss : 0.07714  Real : [8 7 7 8]  Pred : [8 7 7 8]
Index : 274  Loss : 0.02988  Real : [8 9 7 7]  Pred : [8 9 7 7]
Index : 275  Loss : 0.18881  Real : [7 7 7 7]  Pred : [7 7 7 7]
Index : 276  Loss : 0.14290  Real : [9 7 7 7]  Pred : [9 7 7 7]
Index : 277  Loss : 0.19306  Real : [7 9 7 9]  Pred : [7 9 7 8]
Index : 278  Loss : 0.01038  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 279  Loss : 0.03029  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 280  Loss : 0.02636  Real : [7 7 7 7]  Pred : [7 7 7 7]
Index : 281  Loss : 0.25265  Real : [7 7 9 8]  Pred : [7 7 9 8]
Index : 282  Loss : 0.04207  Real : [8 9 8 7]  Pred : [8 9 8 7]
Index : 283  Loss : 0.05687  Real : [8 9 9 8]  Pred : [8 9 9 8]
Index : 284  Loss : 0.04428  Real : [9 9 7 7]  Pred : [9 9 7 7]
Index : 285  Loss : 0.06725  Real : [7 9 8 7]  Pred : [7 9 8 7]
Index : 286  Loss : 0.05519  Real : [9 8

Index : 401  Loss : 0.21721  Real : [9 7 7 9]  Pred : [9 7 7 8]
Index : 402  Loss : 0.01813  Real : [9 8 7 7]  Pred : [9 8 7 7]
Index : 403  Loss : 0.04230  Real : [8 9 9 7]  Pred : [8 9 9 7]
Index : 404  Loss : 0.01848  Real : [7 7 7 9]  Pred : [7 7 7 9]
Index : 405  Loss : 0.26226  Real : [8 8 8 9]  Pred : [8 8 8 8]
Index : 406  Loss : 0.06220  Real : [8 8 7 9]  Pred : [8 8 7 8]
Index : 407  Loss : 0.24268  Real : [7 7 7 8]  Pred : [7 7 7 8]
Index : 408  Loss : 0.05251  Real : [9 8 9 8]  Pred : [9 8 9 8]
Index : 409  Loss : 0.10172  Real : [7 8 8 9]  Pred : [7 8 8 9]
Index : 410  Loss : 0.09756  Real : [7 7 9 7]  Pred : [7 7 9 7]
Index : 411  Loss : 0.02975  Real : [8 7 8 7]  Pred : [8 7 8 7]
Index : 412  Loss : 0.01546  Real : [8 9 9 9]  Pred : [8 9 9 9]
Index : 413  Loss : 0.02330  Real : [8 9 9 7]  Pred : [8 9 9 7]
Index : 414  Loss : 0.22677  Real : [7 8 9 9]  Pred : [7 8 9 7]
Index : 415  Loss : 0.04456  Real : [8 9 7 9]  Pred : [8 9 7 9]
Index : 416  Loss : 0.06043  Real : [9 9

In [5]:
print("fsdg")

fsdg
